name: Check code quality

on:
  pull_request:
    branches:
      - homework_2

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Run formatters
        run: |
          python -m black --check . && python -m isort --check . && flake8 .
