name: Check code quality

on: [pull_request]

jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
        - uses: Install dependencies
        run: pip install black ruff isort
        - uses: Run fommaters
        run: python -m black --check . && python -m isort --check .
